version: '3'

networks:
  default:
    external: true
    name: zabbix

services:
  zbx-frontend-apache:
    image: zbx-frontend-apache
    ports:
      - "80:80"
    command: /usr/sbin/httpd -DFOREGROUND
