FROM zbx-base

RUN yum install -y miracle-zbx-web-{mysql,japanese} && \
    sed -i -e 's/^#//g' -e '/AllowOverride/s/$/ AuthConfig/' /etc/httpd/conf.d/zabbix.conf

COPY ./zabbix.conf.php /etc/zabbix/web/
COPY ./_htaccess /usr/share/zabbix/.htaccess
COPY ./_htdigest /etc/zabbix/web/.htdigest

EXPOSE 80

CMD [ "/usr/sbin/httpd", "-DFOREGROUND" ]
