version: '3'

networks:
  default:
    external:
      name: zabbix

volumes:
  zbx-db:

services:
  zbx-db:
    image: mysql:5.7
    volumes:
      - zbx-db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  zbx-server:
    image: zbx-server
    volumes:
      - ./base/scripts:/etc/zabbix/alertscripts
      - ./base/scripts:/etc/zabbix/externalscripts
    links:
      - zbx-db
    ports:
      - "10051:10051"
    environment:
      - MIBDIRS=/usr/share/snmp/mibs
      - MIBS=ALL
    user: zabbix:zabbix
    command: /usr/sbin/zabbix_server -f -c /etc/zabbix/zabbix_server.conf

  zbx-agent:
    image: zbx-agent
    volumes:
      - ./base/scripts:/etc/zabbix/externalscripts
      - ./agent/conf.d:/etc/zabbix/zabbix_agentd.d
    links:
      - zbx-server
    expose:
      - "10050"
    user: zabbix:zabbix
    command: /usr/sbin/zabbix_agentd -f -c /etc/zabbix/zabbix_agentd.conf
